version: "1.0"
services:
  image:
    build: .
    restart: always
    ports:
      - 22:22
      - ${WEBMIN_ROOT_PORT_PREFIX}0:${WEBMIN_ROOT_PORT_PREFIX}0
      - ${WEBMIN_ROOT_PORT_PREFIX}1:${WEBMIN_ROOT_PORT_PREFIX}1
      - ${WEBMIN_ROOT_PORT_PREFIX}2:${WEBMIN_ROOT_PORT_PREFIX}2
      - ${WEBMIN_ROOT_PORT_PREFIX}3:${WEBMIN_ROOT_PORT_PREFIX}3
      - ${WEBMIN_ROOT_PORT_PREFIX}4:${WEBMIN_ROOT_PORT_PREFIX}4
      - ${WEBMIN_ROOT_PORT_PREFIX}5:${WEBMIN_ROOT_PORT_PREFIX}5
      - ${WEBMIN_ROOT_PORT_PREFIX}6:${WEBMIN_ROOT_PORT_PREFIX}6
      - ${WEBMIN_ROOT_PORT_PREFIX}7:${WEBMIN_ROOT_PORT_PREFIX}7
      - ${WEBMIN_ROOT_PORT_PREFIX}8:${WEBMIN_ROOT_PORT_PREFIX}8
      - ${WEBMIN_ROOT_PORT_PREFIX}9:${WEBMIN_ROOT_PORT_PREFIX}9
      - 53:53/udp
      - 53:53/tcp
      - 80:80
      - 443:443
      - 3306:3306
      - 5432:5432
    env_file:
      - .env
    platform: linux/amd64
    volumes:
      - ./mount/nginx/conf:/usr/local/conf
      - ./mount/home:/home
      - ./mount/mysql/data:/var/lib/mysql
      - ./mount/postgres/data:/var/lib/postgresql/data
      - ./mount/ssh/config:/etc/ssh

    stop_grace_period: 0s