version: "3.8"
services:
  image:
    build:
      context: .
      args:
        WEBMIN_ROOT_HOSTNAME: ${WEBMIN_ROOT_HOSTNAME}
        WEBMIN_ROOT_PASSWORD: ${WEBMIN_ROOT_PASSWORD}
        WEBMIN_ROOT_PORT: ${WEBMIN_ROOT_PORT_PREFIX}0
    restart: always
    ports:
      - 22:22
      - ${WEBMIN_ROOT_PORT_PREFIX}0:${WEBMIN_ROOT_PORT_PREFIX}0
      - ${WEBMIN_ROOT_PORT_PREFIX}1:${WEBMIN_ROOT_PORT_PREFIX}1
      - ${WEBMIN_ROOT_PORT_PREFIX}2:${WEBMIN_ROOT_PORT_PREFIX}2
      - ${WEBMIN_ROOT_PORT_PREFIX}3:${WEBMIN_ROOT_PORT_PREFIX}3
      - ${WEBMIN_ROOT_PORT_PREFIX}4:${WEBMIN_ROOT_PORT_PREFIX}4
      - ${WEBMIN_ROOT_PORT_PREFIX}5:${WEBMIN_ROOT_PORT_PREFIX}5
      - ${WEBMIN_ROOT_PORT_PREFIX}6:${WEBMIN_ROOT_PORT_PREFIX}6
      - ${WEBMIN_ROOT_PORT_PREFIX}7:${WEBMIN_ROOT_PORT_PREFIX}7
      - ${WEBMIN_ROOT_PORT_PREFIX}8:${WEBMIN_ROOT_PORT_PREFIX}8
      - ${WEBMIN_ROOT_PORT_PREFIX}9:${WEBMIN_ROOT_PORT_PREFIX}9
      - 53:53/udp
      - 53:53/tcp
      - 80:80
      - 443:443
      - 3306:3306
      - 5432:5432
    env_file:
      - .env
    platform: linux/amd64
    volumes:
      - ./mount/etc/nginx:/usr/local/conf
      - ./mount/etc/ssh:/etc/ssh
      - ./mount/etc/webmin:/etc/webmin
      - ./mount/etc/sysconfig:/etc/sysconfig
      - ./mount/data/mysql:/var/lib/mysql
      - ./mount/data/home:/home
      - ./mount/data/postgresql:/var/lib/postgresql/data
      - ./mount/data/named:/var/named
    stop_grace_period: 0s