version: "3.8"
services:
  domcloud:
    build:
      context: .
      args:
        WEBMIN_ROOT_HOSTNAME: ${WEBMIN_ROOT_HOSTNAME}
        WEBMIN_ROOT_PASSWORD: ${WEBMIN_ROOT_PASSWORD}
        WEBMIN_ROOT_PORT_PREFIX: ${WEBMIN_ROOT_PORT_PREFIX}
    restart: always
    privileged: true
    hostname: ${WEBMIN_ROOT_HOSTNAME}
    container_name: ${WEBMIN_ROOT_HOSTNAME}
    network_mode: ${NET_MODE:-bridge}
    ports:
    - ${IP_MODE:-0.0.0.0}:80:80
    - ${IP_MODE:-0.0.0.0}:443:443
    - ${IP_MODE:-0.0.0.0}:2212:2212
    - ${IP_MODE:-0.0.0.0}:3306:3306
    - ${IP_MODE:-0.0.0.0}:5432:5432
    - ${IP_MODE:-0.0.0.0}:${WEBMIN_ROOT_PORT_PREFIX}0:${WEBMIN_ROOT_PORT_PREFIX}0
    - ${IP_MODE:-0.0.0.0}:${WEBMIN_ROOT_PORT_PREFIX}1:${WEBMIN_ROOT_PORT_PREFIX}1
    - ${IP_MODE:-0.0.0.0}:${WEBMIN_ROOT_PORT_PREFIX}2:${WEBMIN_ROOT_PORT_PREFIX}2
    - ${IP_MODE:-0.0.0.0}:${WEBMIN_ROOT_PORT_PREFIX}3:${WEBMIN_ROOT_PORT_PREFIX}3
    - ${IP_MODE:-0.0.0.0}:${WEBMIN_ROOT_PORT_PREFIX}4:${WEBMIN_ROOT_PORT_PREFIX}4
    - ${IP_MODE:-0.0.0.0}:${WEBMIN_ROOT_PORT_PREFIX}5:${WEBMIN_ROOT_PORT_PREFIX}5
    - ${IP_MODE:-0.0.0.0}:${WEBMIN_ROOT_PORT_PREFIX}6:${WEBMIN_ROOT_PORT_PREFIX}6
    - ${IP_MODE:-0.0.0.0}:${WEBMIN_ROOT_PORT_PREFIX}7:${WEBMIN_ROOT_PORT_PREFIX}7
    - ${IP_MODE:-0.0.0.0}:${WEBMIN_ROOT_PORT_PREFIX}8:${WEBMIN_ROOT_PORT_PREFIX}8
    - ${IP_MODE:-0.0.0.0}:${WEBMIN_ROOT_PORT_PREFIX}9:${WEBMIN_ROOT_PORT_PREFIX}9
    dns:
    - 127.0.0.1
    - 1.1.1.1
    - 1.0.0.1
    env_file:
      - .env
    platform: linux/${ARCH_MODE:-amd64}
    volumes:
      - ./mount/etc:/etc
      - ./mount/data/mysql:/var/lib/mysql
      - ./mount/data/home:/home
      - ./mount/data/postgresql:/var/lib/postgresql
    stop_grace_period: 0s
