version: "3.8"
services:
  domcloud:
    build:
      context: .
      args:
        WEBMIN_ROOT_HOSTNAME: ${WEBMIN_ROOT_HOSTNAME}
        WEBMIN_ROOT_PASSWORD: ${WEBMIN_ROOT_PASSWORD}
        WEBMIN_ROOT_PORT_PREFIX: ${WEBMIN_ROOT_PORT_PREFIX}
    restart: always
    privileged: true
    hostname: ${WEBMIN_ROOT_HOSTNAME}
    container_name: ${WEBMIN_ROOT_HOSTNAME}
    network_mode: host # Linux only!
    dns:
    - 127.0.0.1
    - 1.1.1.1
    - 1.0.0.1
    env_file:
      - .env
    platform: linux/amd64
    volumes:
      - ./mount/etc/nginx:/etc/nginx
      - ./mount/etc/ssh:/etc/ssh
      - ./mount/etc/webmin:/etc/webmin
      - ./mount/etc/mysql:/etc/mysql
      - ./mount/etc/postgresql:/etc/postgresql
      - ./mount/etc/php:/etc/php
      - ./mount/data/mysql:/var/lib/mysql
      - ./mount/data/home:/home
      - ./mount/data/postgresql:/var/lib/postgresql
      - ./mount/data/bind:/etc/bind
    stop_grace_period: 0s