version: "3.8"
services:
  image:
    build:
      context: .
      args:
        WEBMIN_ROOT_HOSTNAME: ${WEBMIN_ROOT_HOSTNAME}
        WEBMIN_ROOT_PASSWORD: ${WEBMIN_ROOT_PASSWORD}
        WEBMIN_ROOT_PORT_PREFIX: ${WEBMIN_ROOT_PORT_PREFIX}
    restart: always
    privileged: true
    hostname: ${WEBMIN_ROOT_HOSTNAME}
    env_file:
      - .env
    platform: linux/amd64
    volumes:
      - ./mount/etc/nginx:/usr/local/conf
      - ./mount/etc/ssh:/etc/ssh
      - ./mount/etc/webmin:/etc/webmin
      - ./mount/etc/sysconfig:/etc/sysconfig
      - ./mount/data/mysql:/var/lib/mysql
      - ./mount/data/home:/home
      - ./mount/data/postgresql:/var/lib/postgresql/data
      - ./mount/data/named:/var/named
    stop_grace_period: 0s